In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', 130)
pd.set_option('display.max_rows', 130)

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.shape

(59381, 128)

In [5]:
df.head()

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,BMI,Employment_Info_1,Employment_Info_2,Employment_Info_3,Employment_Info_4,Employment_Info_5,Employment_Info_6,InsuredInfo_1,InsuredInfo_2,InsuredInfo_3,InsuredInfo_4,InsuredInfo_5,InsuredInfo_6,InsuredInfo_7,Insurance_History_1,Insurance_History_2,Insurance_History_3,Insurance_History_4,Insurance_History_5,Insurance_History_7,Insurance_History_8,Insurance_History_9,Family_Hist_1,Family_Hist_2,Family_Hist_3,Family_Hist_4,Family_Hist_5,Medical_History_1,Medical_History_2,Medical_History_3,Medical_History_4,Medical_History_5,Medical_History_6,Medical_History_7,Medical_History_8,Medical_History_9,Medical_History_10,Medical_History_11,Medical_History_12,Medical_History_13,Medical_History_14,Medical_History_15,Medical_History_16,Medical_History_17,Medical_History_18,Medical_History_19,Medical_History_20,Medical_History_21,Medical_History_22,Medical_History_23,Medical_History_24,Medical_History_25,Medical_History_26,Medical_History_27,Medical_History_28,Medical_History_29,Medical_History_30,Medical_History_31,Medical_History_32,Medical_History_33,Medical_History_34,Medical_History_35,Medical_History_36,Medical_History_37,Medical_History_38,Medical_History_39,Medical_History_40,Medical_History_41,Medical_Keyword_1,Medical_Keyword_2,Medical_Keyword_3,Medical_Keyword_4,Medical_Keyword_5,Medical_Keyword_6,Medical_Keyword_7,Medical_Keyword_8,Medical_Keyword_9,Medical_Keyword_10,Medical_Keyword_11,Medical_Keyword_12,Medical_Keyword_13,Medical_Keyword_14,Medical_Keyword_15,Medical_Keyword_16,Medical_Keyword_17,Medical_Keyword_18,Medical_Keyword_19,Medical_Keyword_20,Medical_Keyword_21,Medical_Keyword_22,Medical_Keyword_23,Medical_Keyword_24,Medical_Keyword_25,Medical_Keyword_26,Medical_Keyword_27,Medical_Keyword_28,Medical_Keyword_29,Medical_Keyword_30,Medical_Keyword_31,Medical_Keyword_32,Medical_Keyword_33,Medical_Keyword_34,Medical_Keyword_35,Medical_Keyword_36,Medical_Keyword_37,Medical_Keyword_38,Medical_Keyword_39,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48,Response
0,2,1,D3,10,0.076923,2,1,1,0.641791,0.581818,0.148536,0.323008,0.028,12,1,0.0,3,NaN,1,2,6,3,1,2,1,1,1,3,1,0.000667,1,1,2,2,NaN,0.598039,NaN,0.526786,4.0,112,2,1,1,3,2,2,1,NaN,3,2,3,3,240.0,3,3,1,1,2,1,2,3,NaN,1,3,3,1,3,2,3,NaN,1,3,1,2,2,1,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8
1,5,1,A1,26,0.076923,2,3,1,0.059701,0.600000,0.131799,0.272288,0.000,1,3,0.0,2,0.0018,1,2,6,3,1,2,1,2,1,3,1,0.000133,1,3,2,2,0.188406,NaN,0.084507,NaN,5.0,412,2,1,1,3,2,2,1,NaN,3,2,3,3,0.0,1,3,1,1,2,1,2,3,NaN,1,3,3,1,3,2,3,NaN,3,1,1,2,2,1,3,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4
2,6,1,E1,26,0.076923,2,3,1,0.029851,0.745455,0.288703,0.428780,0.030,9,1,0.0,2,0.0300,1,2,8,3,1,1,1,2,1,1,3,NaN,3,2,3,3,0.304348,NaN,0.225352,NaN,10.0,3,2,2,1,3,2,2,2,NaN,3,2,3,3,NaN,1,3,1,1,2,1,2,3,NaN,2,2,3,1,3,2,3,NaN,3,3,1,3,2,1,3,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8
3,7,1,D4,10,0.487179,2,3,1,0.164179,0.672727,0.205021,0.352438,0.042,9,1,0.0,3,0.2000,2,2,8,3,1,2,1,2,1,1,3,NaN,3,2,3,3,0.420290,NaN,0.352113,NaN,0.0,350,2,2,1,3,2,2,2,NaN,3,2,3,3,NaN,1,3,1,1,2,2,2,3,NaN,1,3,3,1,3,2,3,NaN,3,3,1,2,2,1,3,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8
4,8,1,D2,26,0.230769,2,3,1,0.417910,0.654545,0.234310,0.424046,0.027,9,1,0.0,2,0.0500,1,2,6,3,1,2,1,2,1,1,3,NaN,3,2,3,2,0.463768,NaN,0.408451,NaN,NaN,162,2,2,1,3,2,2,2,NaN,3,2,3,3,NaN,1,3,1,1,2,1,2,3,NaN,2,2,3,1,3,2,3,NaN,3,3,1,3,2,1,3,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8

In [6]:
df['Response'].value_counts()/df.shape[0]

8    0.328203
6    0.189168
7    0.135178
2    0.110338
1    0.104528
5    0.091477
4    0.024048
3    0.017059
Name: Response, dtype: float64

In [7]:
df.dtypes

Id                       int64
Product_Info_1           int64
Product_Info_2          object
Product_Info_3           int64
Product_Info_4         float64
Product_Info_5           int64
Product_Info_6           int64
Product_Info_7           int64
Ins_Age                float64
Ht                     float64
Wt                     float64
BMI                    float64
Employment_Info_1      float64
Employment_Info_2        int64
Employment_Info_3        int64
Employment_Info_4      float64
Employment_Info_5        int64
Employment_Info_6      float64
InsuredInfo_1            int64
InsuredInfo_2            int64
InsuredInfo_3            int64
InsuredInfo_4            int64
InsuredInfo_5            int64
InsuredInfo_6            int64
InsuredInfo_7            int64
Insurance_History_1      int64
Insurance_History_2      int64
Insurance_History_3      int64
Insurance_History_4      int64
Insurance_History_5    float64
Insurance_History_7      int64
Insurance_History_8      int64
Insurance_History_9      int64
Family_Hist_1            int64
Family_Hist_2          float64
Family_Hist_3          float64
Family_Hist_4          float64
Family_Hist_5          float64
Medical_History_1      float64
Medical_History_2        int64
Medical_History_3        int64
Medical_History_4        int64
Medical_History_5        int64
Medical_History_6        int64
Medical_History_7        int64
Medical_History_8        int64
Medical_History_9        int64
Medical_History_10     float64
Medical_History_11       int64
Medical_History_12       int64
Medical_History_13       int64
Medical_History_14       int64
Medical_History_15     float64
Medical_History_16       int64
Medical_History_17       int64
Medical_History_18       int64
Medical_History_19       int64
Medical_History_20       int64
Medical_History_21       int64
Medical_History_22       int64
Medical_History_23       int64
Medical_History_24     float64
Medical_History_25       int64
Medical_History_26       int64
Medical_History_27       int64
Medical_History_28       int64
Medical_History_29       int64
Medical_History_30       int64
Medical_History_31       int64
Medical_History_32     float64
Medical_History_33       int64
Medical_History_34       int64
Medical_History_35       int64
Medical_History_36       int64
Medical_History_37       int64
Medical_History_38       int64
Medical_History_39       int64
Medical_History_40       int64
Medical_History_41       int64
Medical_Keyword_1        int64
Medical_Keyword_2        int64
Medical_Keyword_3        int64
Medical_Keyword_4        int64
Medical_Keyword_5        int64
Medical_Keyword_6        int64
Medical_Keyword_7        int64
Medical_Keyword_8        int64
Medical_Keyword_9        int64
Medical_Keyword_10       int64
Medical_Keyword_11       int64
Medical_Keyword_12       int64
Medical_Keyword_13       int64
Medical_Keyword_14       int64
Medical_Keyword_15       int64
Medical_Keyword_16       int64
Medical_Keyword_17       int64
Medical_Keyword_18       int64
Medical_Keyword_19       int64
Medical_Keyword_20       int64
Medical_Keyword_21       int64
Medical_Keyword_22       int64
Medical_Keyword_23       int64
Medical_Keyword_24       int64
Medical_Keyword_25       int64
Medical_Keyword_26       int64
Medical_Keyword_27       int64
Medical_Keyword_28       int64
Medical_Keyword_29       int64
Medical_Keyword_30       int64
Medical_Keyword_31       int64
Medical_Keyword_32       int64
Medical_Keyword_33       int64
Medical_Keyword_34       int64
Medical_Keyword_35       int64
Medical_Keyword_36       int64
Medical_Keyword_37       int64
Medical_Keyword_38       int64
Medical_Keyword_39       int64
Medical_Keyword_40       int64
Medical_Keyword_41       int64
Medical_Keyword_42       int64
Medical_Keyword_43       int64
Medical_Keyword_44       int64
Medical_Keyword_45       int64
Medical_Keyword_46       int64
Medical_Keyword_47       int64
Medical_Keyword_48       int64
Response                 int64
dtype: object

In [9]:
colu = ['Product_Info_1', 'Product_Info_2','Product_Info_3', 'Product_Info_5', 'Product_Info_6', 'Product_Info_7', 
   'Employment_Info_2', 'Employment_Info_3', 'Employment_Info_5', 'InsuredInfo_1', 'InsuredInfo_2', 'InsuredInfo_3', 
   'InsuredInfo_4', 'InsuredInfo_5', 'InsuredInfo_6', 'InsuredInfo_7', 'Insurance_History_1', 'Insurance_History_2', 
   'Insurance_History_3', 'Insurance_History_4', 'Insurance_History_7', 'Insurance_History_8', 'Insurance_History_9', 
   'Family_Hist_1', 'Medical_History_2', 'Medical_History_3', 'Medical_History_4', 'Medical_History_5', 'Medical_History_6', 
   'Medical_History_7', 'Medical_History_8', 'Medical_History_9', 'Medical_History_11', 'Medical_History_12', 
   'Medical_History_13', 'Medical_History_14', 'Medical_History_16', 'Medical_History_17', 'Medical_History_18', 
   'Medical_History_19', 'Medical_History_20', 'Medical_History_21', 'Medical_History_22', 'Medical_History_23', 
   'Medical_History_25', 'Medical_History_26', 'Medical_History_27', 'Medical_History_28', 'Medical_History_29', 
   'Medical_History_30', 'Medical_History_31', 'Medical_History_33', 'Medical_History_34', 'Medical_History_35', 
   'Medical_History_36', 'Medical_History_37', 'Medical_History_38', 'Medical_History_39', 'Medical_History_40', 
   'Medical_History_41']

In [10]:
df[colu] = df[colu].astype(str)

In [11]:
df.index = df.Id

In [12]:
df.drop(['Id','Medical_History_10','Medical_History_32','Medical_History_24',
'Medical_History_15',
'Family_Hist_5',
'Family_Hist_3',
'Family_Hist_2',],axis=1,inplace=True)

In [13]:
df.shape

(59381, 120)

In [14]:

df.select_dtypes(include=['object']).columns

Index(['Product_Info_1', 'Product_Info_2', 'Product_Info_3', 'Product_Info_5',
       'Product_Info_6', 'Product_Info_7', 'Employment_Info_2',
       'Employment_Info_3', 'Employment_Info_5', 'InsuredInfo_1',
       'InsuredInfo_2', 'InsuredInfo_3', 'InsuredInfo_4', 'InsuredInfo_5',
       'InsuredInfo_6', 'InsuredInfo_7', 'Insurance_History_1',
       'Insurance_History_2', 'Insurance_History_3', 'Insurance_History_4',
       'Insurance_History_7', 'Insurance_History_8', 'Insurance_History_9',
       'Family_Hist_1', 'Medical_History_2', 'Medical_History_3',
       'Medical_History_4', 'Medical_History_5', 'Medical_History_6',
       'Medical_History_7', 'Medical_History_8', 'Medical_History_9',
       'Medical_History_11', 'Medical_History_12', 'Medical_History_13',
       'Medical_History_14', 'Medical_History_16', 'Medical_History_17',
       'Medical_History_18', 'Medical_History_19', 'Medical_History_20',
       'Medical_History_21', 'Medical_History_22', 'Medical_History_23',
       'Medical_History_25', 'Medical_History_26', 'Medical_History_27',
       'Medical_History_28', 'Medical_History_29', 'Medical_History_30',
       'Medical_History_31', 'Medical_History_33', 'Medical_History_34',
       'Medical_History_35', 'Medical_History_36', 'Medical_History_37',
       'Medical_History_38', 'Medical_History_39', 'Medical_History_40',
       'Medical_History_41'],
      dtype='object')

In [15]:
df.isnull().sum().sort_values(ascending=False)

Insurance_History_5    25396
Family_Hist_4          19184
Employment_Info_6      10854
Medical_History_1       8889
Employment_Info_4       6779
Employment_Info_1         19
Response                   0
Medical_History_8          0
Medical_History_11         0
Medical_History_9          0
Medical_History_5          0
Medical_History_7          0
Medical_History_6          0
Medical_History_4          0
Medical_History_3          0
Medical_History_2          0
Medical_History_12         0
Medical_History_13         0
Insurance_History_9        0
Medical_History_14         0
Medical_History_16         0
Medical_History_17         0
Medical_History_18         0
Medical_History_19         0
Medical_History_20         0
Medical_History_21         0
Medical_History_22         0
Medical_History_23         0
Medical_History_25         0
Medical_History_26         0
Medical_History_27         0
Family_Hist_1              0
Insurance_History_7        0
Insurance_History_8        0
Employment_Info_3          0
Product_Info_2             0
Product_Info_3             0
Product_Info_4             0
Product_Info_5             0
Product_Info_6             0
Product_Info_7             0
Ins_Age                    0
Ht                         0
Wt                         0
BMI                        0
Employment_Info_2          0
Employment_Info_5          0
Medical_Keyword_48         0
InsuredInfo_1              0
InsuredInfo_2              0
InsuredInfo_3              0
InsuredInfo_4              0
InsuredInfo_5              0
InsuredInfo_6              0
InsuredInfo_7              0
Insurance_History_1        0
Insurance_History_2        0
Insurance_History_3        0
Insurance_History_4        0
Medical_History_28         0
Medical_History_29         0
Medical_History_30         0
Medical_Keyword_34         0
Medical_Keyword_22         0
Medical_Keyword_23         0
Medical_Keyword_24         0
Medical_Keyword_25         0
Medical_Keyword_26         0
Medical_Keyword_27         0
Medical_Keyword_28         0
Medical_Keyword_29         0
Medical_Keyword_30         0
Medical_Keyword_31         0
Medical_Keyword_32         0
Medical_Keyword_33         0
Medical_Keyword_35         0
Medical_Keyword_20         0
Medical_Keyword_36         0
Medical_Keyword_37         0
Medical_Keyword_38         0
Medical_Keyword_39         0
Medical_Keyword_40         0
Medical_Keyword_41         0
Medical_Keyword_42         0
Medical_Keyword_43         0
Medical_Keyword_44         0
Medical_Keyword_45         0
Medical_Keyword_46         0
Medical_Keyword_47         0
Medical_Keyword_21         0
Medical_Keyword_19         0
Medical_History_31         0
Medical_Keyword_4          0
Medical_History_33         0
Medical_History_34         0
Medical_History_35         0
Medical_History_36         0
Medical_History_37         0
Medical_History_38         0
Medical_History_39         0
Medical_History_40         0
Medical_History_41         0
Medical_Keyword_1          0
Medical_Keyword_2          0
Medical_Keyword_3          0
Medical_Keyword_5          0
Medical_Keyword_18         0
Medical_Keyword_6          0
Medical_Keyword_7          0
Medical_Keyword_8          0
Medical_Keyword_9          0
Medical_Keyword_10         0
Medical_Keyword_11         0
Medical_Keyword_12         0
Medical_Keyword_13         0
Medical_Keyword_14         0
Medical_Keyword_15         0
Medical_Keyword_16         0
Medical_Keyword_17         0
Product_Info_1             0
dtype: int64

In [16]:
df[['Insurance_History_5',
'Family_Hist_4',
'Employment_Info_6',
'Medical_History_1',
'Employment_Info_4',
'Employment_Info_1']].describe()

,Insurance_History_5,Family_Hist_4,Employment_Info_6,Medical_History_1,Employment_Info_4,Employment_Info_1
count,33985.000000,40197.000000,48527.000000,50492.000000,52602.000000,59362.000000
mean,0.001733,0.444890,0.361469,7.962172,0.006283,0.077582
std,0.007338,0.163012,0.349551,13.027697,0.032816,0.082347
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000400,0.323944,0.060000,2.000000,0.000000,0.035000
50%,0.000973,0.422535,0.250000,4.000000,0.000000,0.060000
75%,0.002000,0.563380,0.550000,9.000000,0.000000,0.100000
max,1.000000,0.943662,1.000000,240.000000,1.000000,1.000000

In [17]:
df.fillna(df.mean, axis=1, inplace=True)

In [18]:
dummy = pd.get_dummies(df[colu], drop_first =True)

In [19]:
numeric = df.select_dtypes(exclude=['object'])

In [20]:
train = numeric.merge(dummy, left_index=True, right_index=True)

In [22]:
train.shape

(59381, 823)

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [24]:
y = train.loc[:,['Response']]

In [25]:
train.drop('Response', axis=1, inplace=True)

In [26]:
train.shape

(59381, 822)

In [27]:
X, y  = train.values, y.values

In [ ]:

X_train , X_val, y_train, y_test = train_test_split(X, y, test_size=.1, random_state=23)

In [ ]:
pca = PCA(n_components=.99,)
X_train_pca = pca.fit_transform(X_train)
X_val_pca = pca.transform(X_val)

In [22]:
X_train_pca.shape

(53442, 194)

In [38]:
X_train.shape

(53442, 822)

In [55]:
from sklearn.linear_model import LogisticRegression

In [72]:
lr = LogisticRegression(class_weight='balanced', penalty='l2',verbose=2)

In [73]:
lr.fit(X_train, y_train.ravel())

[LibLinear]

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=2, warm_start=False)

In [75]:
lr.score(X_val, y_test)

0.44435090082505474

In [74]:
lr.score(X_train, y_train)

0.47245612065416714

In [49]:
y_train.ravel()

array([7, 8, 8, ..., 2, 8, 8])

In [23]:
from sklearn.svm import SVC

In [24]:
sv = SVC()

In [25]:
sv.fit(X_train_pca, y_train.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
sv.score(X_val_pca, y_test)

0.4689341640006735

In [ ]:
sv.score(X_train_pca, y_train)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_range = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0 , 100.0 ,1000.0]
param_grid = [{'svc__C':param_range, 'svc__kernel':['linear']},
               {'svc__C':param_range, 'svc__kernel':['rbf'], 'svc__gamma':param_range}]

gs = GridSearchCV(estimator=sv,
                 param_grid=param_grid,
                 scoring='accuracy',
                 cv=10)

gs = gs.fit(X_train_pca, y_train.ravel())
print('Best average Precision : ', gs.best_score_)
print(gs.best_params_)